site_name: Github-Terraform
site_description: Terraform import of your Github
copyright: Made with ❤️ by Me
repo_name: wesleimp/github-terraform
repo_url: https://github.com/wesleimp/github-terraform
edit_uri: edit/master/www/docs/
dev_addr: 0.0.0.0:8000

theme:
  name: material
  palette:
    primary: deep-purple
    accent: deep-purple
  language: en
  custom_dir: docs/overrides
  # logo: static/avatar.png
  # favicon: static/favicon.ico
  include_search_page: false
  search_index_only: true

plugins:
  # disable temporarely because its freezing the page
  - search:
      prebuild_index: python
      lang:
        - en
  - minify:
      minify_html: true


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/wesleimp
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wesleimp

nav:
- Home: index.md
- install.md
- CLI:
  - cli/issue_labels.md
  - cli/repositories.md
  - cli/repository_collaborator.md
  - cli/teams.md

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences